In [3]:
import cv2
# from google.colab.patches import cv2_imshow
import numpy as np

# buka citra
img = cv2.imread('Lenna.png')

In [4]:
row, col, ch = img.shape

kanvas_hsv = np.zeros((row, col, 3), np.uint8)

In [11]:
kanvas_hsv[0][0][0]=255
print(kanvas_hsv)

[[[255   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]


In [4]:
# ubah citra tersebut menjadi HSV Color space.
for i in range (0, row):
  for j in range (0, col):
    b = img[i,j,0]/255
    g = img[i,j,1]/255
    r = img[i,j,2]/255

    vmax = max(r, g, b)
    vmin = min(r, g, b)
    # v
    v = vmax
    valv_min = v - vmin
    # s
    s = valv_min/v if v != 0 else 0
    # h
    if v == r :
      h = (60*(g-b))/valv_min
    elif v == g :
      h = ((120+60)*(b-r))/valv_min
    elif v == b :
      h = ((240+60)*(b-r))/valv_min
    elif r == g and g == b :
      h = 0
    h = h + 360 if h < 0 else h


    kanvas_hsv[i,j,0] = h/2
    kanvas_hsv[i,j,1] = s*255
    kanvas_hsv[i,j,2] = v*255




In [5]:
cv2.imshow("gess",kanvas_hsv)

In [6]:
# split citra menggunakan fungsi cv.split
h,s,v = cv2.split(kanvas_hsv)

In [7]:
# jumlahkan setiap channel hsv menggunakan looping
total_h = 0
total_s = 0
total_v = 0
for i in range (0, row):
  for j in range (0, col):
    # h
    total_h += h[i][j]
    # s
    total_s += s[i][j]
    # v
    total_v += v[i][j]


n = col * row
# rata-rata channel h
rata_h = total_h / n
# rata-rata channel s
rata_s = total_s / n
# rata-rata channel v
rata_v = total_v / n

In [8]:
# lakukan thresholding manual menggunakan looping
for i in range (0, row):
  for j in range (0, col):
    # h
    if (kanvas_hsv[i,j,0] < rata_h):
      kanvas_hsv[i,j,0] = 0
    else:
      kanvas_hsv[i,j,0] = 255

    # s
    if (kanvas_hsv[i,j,1] < rata_s):
      kanvas_hsv[i,j,1] = 0
    else:
      kanvas_hsv[i,j,1] = 255

    # v
    if (kanvas_hsv[i,j,2] < rata_v):
      kanvas_hsv[i,j,2] = 0
    else:
      kanvas_hsv[i,j,2] = 255

cv2.imwrite("gambar-hue",kanvas_hsv[:,:,0])
cv2.imwrite("gambar-saturation",kanvas_hsv[:,:,1])
cv2.imwrite("gambar-value",kanvas_hsv[:,:,2])
# cv2.imshow(kanvas_hsv[:,:,0])
# cv2.imshow(kanvas_hsv[:,:,1])
# cv2.imshow(kanvas_hsv[:,:,2])

error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:696: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'cv::imwrite_'


: 