# Pertemuan 3

## Modules & Pakckages di dalam Python

### Apa itu Modules?
Pada saat kita membuat kode program, kemudian kita mengerjakannya ke dalam 1 file python, sehingga ada banyak baris kode yang kita tuliskan ke dalam 1 file python (*.py) tersebut. Kesulitan yang dapat terjadi adalah jika kita ingin me-maintenance kode program yang sudah kita buat jika kita menuliskan kode python pada 1 file yang besar. Kemungkinan untuk proses tracing error yang menyulitkan dan harus mengecek baris perbaris dari kode tersebut.Jika banyak developer yang mengerjakan, juga akan sulit dengan hanya 1 file tersebut. <br>
Salah satu cara untuk mengetasi hal ini adalah, kita dapat mendekomposisi dari task besar menjadi task-task kecil pada file python yang berbeda yang memungkinkan dapat dikerjakan oleh banyak developer, tidak hanya 1 developer saja. task-task kecil tersebut dapat diartikan sebagai module dalam konsep bahasa pemrograman python.<br>

jadi apa itu module? module didefinisikan sebagai file-file berisikan python definitions dan statements, yang kemudian nanti dapat diimport pada saat dibutuhkan.

Untuk menggunakan module dapat dilakukan dengan 2 cara, pertama (yang paling umum)kita menggunakan module yang sudah ada (ditulis oleh orang lain) saat mengerjakan project yang kompleks. Hal ini disebut module's user;<br>
Yang kedua kita membuat module baru, untuk kepentingan sendiri, atau membantu programmer lain sehngga dapat digunakan untuk mengerjakan projetnya, ini disebut module's supplier.
Untuk menggunakan module, kita harus mengetahui namanya terlebih dahulu. beberapa module sudah terintegrasi dengan python, bersama dengan built-in function pyhton (dari python standard library). Setiap module berisikan entities, dimana dapat berupa function, nilai konstans, classes, dan object.

Contoh module yang sering digunakan yaitu module dengan nama <mark> math </mark>. Module tersebut berisikan banyak koleksi fungsi matematika. Programmer yang membutuhkan fungsi-fungsi matematika dalam kode programnya seperti <mark>sin()</mark>, <mark>cos()</mark>, tidak harus membuat fungsi matematika tersebut, namun dapat menggunakan koleksi fungsi dari module <mark> math </mark> tersebut.


### Importing Module
Untuk dapat menggunakan module, kita harus terlebih dauhulu meng-import module agar entitiesnya bisa kita gunakan. Keyword yang digunakan adalah <mark> import </mark>, untuk dapat memanggil module ke dalam script python.

In [2]:
# Contoh untuk mengimport module:
import math
import sys
import os

In [3]:
# Contoh untuk mengimport module:
import math, sys, os, platform

In [4]:
# Contoh untuk menggunakan entities dari module yang sudah diimmport
#print(math.sin(math.pi/2))
#print(sys.version)
#print(os.getcwd())
print(math.sin(30))
print(math.pi)
print(sys.version)
print(os.getcwd())

-0.9880316240928618
3.141592653589793
3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
/home/ghandi-dev/Desktop/citra-digital


In [5]:
import math
print(math.pow(4,3)) #entities fungsi di module math

def pow(a,b):
    return float(a**b)
print(pow(4,3))

64.0
64.0


In [6]:
import math as sipp
print(sipp.pi)
print(sipp.pow(2,3))
print(sipp.sin(1))

3.141592653589793
8.0
0.8414709848078965


In [7]:
#from math import pow, pi, sin, cos # from module import entities
from math import*

print(pow(2,3))
print(pi)
print(sin(0))
print(cos(1))
print(sqrt(8))


def sqrt2(x):
    return(x**0.5)

print(sqrt2(8))

8.0
3.141592653589793
0.0
0.5403023058681398
2.8284271247461903
2.8284271247461903


In [8]:
for name in dir(math):
    print(name, end="\t")

__doc__	__loader__	__name__	__package__	__spec__	acos	acosh	asin	asinh	atan	atan2	atanh	ceil	comb	copysign	cos	cosh	degrees	dist	e	erf	erfc	exp	expm1	fabs	factorial	floor	fmod	frexp	fsum	gamma	gcd	hypot	inf	isclose	isfinite	isinf	isnan	isqrt	lcm	ldexp	lgamma	log	log10	log1p	log2	modf	nan	nextafter	perm	pi	pow	prod	radians	remainder	sin	sinh	sqrt	tan	tanh	tau	trunc	ulp	

**Berikut ini akan diberikan contoh-contoh penggunaan module yang umum di python. Beberapa module itu adalah random, platform, os, dll**
Daftar module dapat dilihat di link berikut: https://docs.python.org/3/py-modindex.html

In [9]:
# Module Random digunakan untuk membangkitkan bilangan acak
import random as rnd
for name in dir(rnd):
    print(name, end="\t")

BPF	LOG4	NV_MAGICCONST	RECIP_BPF	Random	SG_MAGICCONST	SystemRandom	TWOPI	_ONE	_Sequence	_Set	__all__	__builtins__	__cached__	__doc__	__file__	__loader__	__name__	__package__	__spec__	_accumulate	_acos	_bisect	_ceil	_cos	_e	_exp	_floor	_index	_inst	_isfinite	_log	_os	_pi	_random	_repeat	_sha512	_sin	_sqrt	_test	_test_generator	_urandom	_warn	betavariate	choice	choices	expovariate	gammavariate	gauss	getrandbits	getstate	lognormvariate	normalvariate	paretovariate	randbytes	randint	random	randrange	sample	seed	setstate	shuffle	triangular	uniform	vonmisesvariate	weibullvariate	

In [10]:
lst1 = ["satu", "dua", "tiga", "empat", "lima"]
lst2 = (1,2,3,4,5,6,7,8,9)

In [35]:
from random import sample,choice
print(choice(lst1))
print(choice(lst2))
print(sample(lst1, 3))
print(sample(lst2, 3))

empat
5
['lima', 'empat', 'satu']
[3, 2, 7]


In [12]:
# Module Platform digunakan untuk mengakses informasi data platform, seperti hardware, operating system, dan interpreter
import platform
for name in dir(platform):
    print(name, end="\t")

_Processor	_WIN32_CLIENT_RELEASES	_WIN32_SERVER_RELEASES	__builtins__	__cached__	__copyright__	__doc__	__file__	__loader__	__name__	__package__	__spec__	__version__	_comparable_version	_component_re	_default_architecture	_follow_symlinks	_get_machine_win32	_ironpython26_sys_version_parser	_ironpython_sys_version_parser	_java_getprop	_libc_search	_mac_ver_xml	_node	_norm_version	_os_release_cache	_os_release_candidates	_os_release_line	_os_release_unescape	_parse_os_release	_platform	_platform_cache	_pypy_sys_version_parser	_sys_version	_sys_version_cache	_sys_version_parser	_syscmd_file	_syscmd_ver	_uname_cache	_unknown_as_blank	_ver_output	_ver_stages	architecture	collections	freedesktop_os_release	functools	itertools	java_ver	libc_ver	mac_ver	machine	node	os	platform	processor	python_branch	python_build	python_compiler	python_implementation	python_revision	python_version	python_version_tuple	re	release	subprocess	sys	system	system_alias	uname	uname_result	version	win32_edition	win32_

In [13]:
from platform import processor, platform, machine, system, version
print(processor())
print(platform())
print(machine())
print(system())
print(version())

x86_64
Linux-6.4.6-76060406-generic-x86_64-with-glibc2.35
x86_64
Linux
#202307241739~1695312586~22.04~4d8f3e9 SMP PREEMPT_DYNAMIC Thu S


In [14]:
# Module os digunakan untuk mengakses informasi data informasi pada operating system
import os
for name in dir(os):
    print(name, end="\t")

CLD_CONTINUED	CLD_DUMPED	CLD_EXITED	CLD_KILLED	CLD_STOPPED	CLD_TRAPPED	DirEntry	EFD_CLOEXEC	EFD_NONBLOCK	EFD_SEMAPHORE	EX_CANTCREAT	EX_CONFIG	EX_DATAERR	EX_IOERR	EX_NOHOST	EX_NOINPUT	EX_NOPERM	EX_NOUSER	EX_OK	EX_OSERR	EX_OSFILE	EX_PROTOCOL	EX_SOFTWARE	EX_TEMPFAIL	EX_UNAVAILABLE	EX_USAGE	F_LOCK	F_OK	F_TEST	F_TLOCK	F_ULOCK	GRND_NONBLOCK	GRND_RANDOM	GenericAlias	MFD_ALLOW_SEALING	MFD_CLOEXEC	MFD_HUGETLB	MFD_HUGE_16GB	MFD_HUGE_16MB	MFD_HUGE_1GB	MFD_HUGE_1MB	MFD_HUGE_256MB	MFD_HUGE_2GB	MFD_HUGE_2MB	MFD_HUGE_32MB	MFD_HUGE_512KB	MFD_HUGE_512MB	MFD_HUGE_64KB	MFD_HUGE_8MB	MFD_HUGE_MASK	MFD_HUGE_SHIFT	Mapping	MutableMapping	NGROUPS_MAX	O_ACCMODE	O_APPEND	O_ASYNC	O_CLOEXEC	O_CREAT	O_DIRECT	O_DIRECTORY	O_DSYNC	O_EXCL	O_FSYNC	O_LARGEFILE	O_NDELAY	O_NOATIME	O_NOCTTY	O_NOFOLLOW	O_NONBLOCK	O_PATH	O_RDONLY	O_RDWR	O_RSYNC	O_SYNC	O_TMPFILE	O_TRUNC	O_WRONLY	POSIX_FADV_DONTNEED	POSIX_FADV_NOREUSE	POSIX_FADV_NORMAL	POSIX_FADV_RANDOM	POSIX_FADV_SEQUENTIAL	POSIX_FADV_WILLNEED	POSIX_SPAWN_CLOSE	POSIX_SPAWN_DUP

## Python Package Installer (PIP)
Pada python, tidak hanya tersedia dari packages yang kita buat sendiri (user), sama seperti modul ada banyak packages yang disuplai oleh developer lain dan tersedia di repositori online salah satu diantaranya yang paling umum dan menjadi referensi utama adalah Python Package Index(PyPI).<br>
Untuk menginstal packages yang tersedia di Repo kita harus menggunakan keyword <mark> **pip**</mark>(pip install packages).

> pip -- version

> pip help

> pip list

> pip install packages_names

> pip install --user packages_names

> pip install packages_names==packages_version

> pip install -U package_name

> pip uninstall package_name

> pip show packages_names

> pip search    ==> https://pypi.org/search/ *sudah tidak ada

## Package Numpy, Pandas untuk Sains Data dan Analisis Numerik

## Numpy
Numpy adalah salah satu package yang banyak digunakan. Numpy merupakan operasi numerik pada python yang dirancang untuk komputasi yang lebih cepat saat bekerja pada arrays berdimensi-n. Sifat dari array numpy adalah mutable.

> import numpy

> import numpy as np

In [15]:
# import numpy

import numpy as np
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__

In [16]:
# Buat array menggunakan numpy (1 Dimensi)
list_a = [0,1,2,3,4,5]
a = np.array([0,1,2,3,4,5])
a1 = np.arange(5)
print(list_a)
print()
print(a)
print()
print(a1)
print()
print(type(a))
print(a.dtype)
print(a.shape)
print(a.ndim)

[0, 1, 2, 3, 4, 5]

[0 1 2 3 4 5]

[0 1 2 3 4]

<class 'numpy.ndarray'>
int64
(6,)
1


In [17]:
# Akses array 1 Dimensi
print(a[0])
print(a[-1])
print(a[:4])
print(a[3:])

0
5
[0 1 2 3]
[3 4 5]


In [18]:
# Buat array menggunakan numpy (2 Dimensi)
b = np.array([[4,5.,8,4],[6,.3,2,1],[8.,6,4,.3]])
print(b)
print(type(b))
print(b.dtype)
print(b.shape)
print(b.ndim)

[[4.  5.  8.  4. ]
 [6.  0.3 2.  1. ]
 [8.  6.  4.  0.3]]
<class 'numpy.ndarray'>
float64
(3, 4)
2


In [19]:
# Akses array 2 Dimensi
print(b[0])
print(b[0][1])
print(b[1][1:4])
print(b[0, 1:4])

[4. 5. 8. 4.]
5.0
[0.3 2.  1. ]
[5. 8. 4.]


In [20]:
# Buat array menggunakan numpy (3 Dimensi)
c = np.array([[[4,5,8,4],[6,3,2,1]],[[8,6,4,3], [4,7,8,9]]])
print(c)
print()
print(type(c))
print(c.dtype)
print(c.shape)
print(c.ndim)

[[[4 5 8 4]
  [6 3 2 1]]

 [[8 6 4 3]
  [4 7 8 9]]]

<class 'numpy.ndarray'>
int64
(2, 2, 4)
3


In [21]:
# Akses array 3 Dimensi
print(c[0])
print()
print(c[0][1])
print()
print(c[1][1][1:3])
print()
print(c[0, 1, 2:])

[[4 5 8 4]
 [6 3 2 1]]

[6 3 2 1]

[7 8]

[2 1]


In [22]:
# membuat Array dengan nilai 0 (zeros), 1 (ones), empty
_a = np.zeros(5)
_b = np.ones((4,3))
_c = np.empty((2,2,4), dtype=np.unicode_)
print(_a)
print()
print(_b)
print()
print(_c)

[0. 0. 0. 0. 0.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[['' '' '' '']
  ['' '' '' '']]

 [['' '' '' '']
  ['' '' '' '']]]


In [23]:
# Mengisi elemen pada numpy
_b[0][1] = 4
_b[1][2] = 6
print(_b)

[[1. 4. 1.]
 [1. 1. 6.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
# Operasi pada array
print(_b + _b)
print()
print(_b * _b)
print()
print(1/_b)

[[ 2.  8.  2.]
 [ 2.  2. 12.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]]

[[ 1. 16.  1.]
 [ 1.  1. 36.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]

[[1.         0.25       1.        ]
 [1.         1.         0.16666667]
 [1.         1.         1.        ]
 [1.         1.         1.        ]]


#### Beberapa fungsi dan method pada numpy

In [25]:
a = np.arange(6)
print(np.sqrt(a))
print(np.max(a))
print(np.min(a))
print(np.exp(a))
print(a.sum())
print(a.mean())
print(np.mean(a))
print(np.sort(a))

[0.         1.         1.41421356 1.73205081 2.         2.23606798]
5
0
[  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]
15
2.5
2.5
[0 1 2 3 4 5]


In [26]:
arr = np.random.randn(10)
print(arr)
print()
print(np.where(arr> 0, True, False))
print()
print(np.where(arr> 0, True, arr))
print()
print(np.where(arr> 0, arr, False))

[-0.33076194 -0.27900365  0.76976237 -1.17487178 -1.08829119 -0.38597108
  1.07457983  0.58778582  0.32630016 -0.91563875]

[False False  True False False False  True  True  True False]

[-0.33076194 -0.27900365  1.         -1.17487178 -1.08829119 -0.38597108
  1.          1.          1.         -0.91563875]

[0.         0.         0.76976237 0.         0.         0.
 1.07457983 0.58778582 0.32630016 0.        ]


In [27]:
# Unique and other set logic
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe', 'Thomas'])
print(np.unique(names))
print(np.in1d(names, 'Will'))

['Bob' 'Joe' 'Thomas' 'Will']
[False False  True False  True False False False]


## Pandas
Pandas merupakan package yang banyak dipakai dalam analisis numerik di dalam python yang bekerja dengan bentuk <mark>**series**</mark> (kolom), dan juga <mark>**dataframe**</mark>(kolom multi-dimensi)
<br>
dengan Pandas, kita dapat membuat representasi visualisasi yang lebih baik dari multi-dimensi data seperti <mark>dictionary</mark>, menjadi data tabular yang nilai keys dinyatakan sebagai header kolom, sedangkan values adalah komponen/elemen kolom.

In [28]:
#!pip install pandas

In [29]:
import pandas as pd

# buat dictionary
dct = {'aple': np.array([1,2,3,4]),
       'oranges' : np.array([6,7,8,9])
      }
print(dct)

{'aple': array([1, 2, 3, 4]), 'oranges': array([6, 7, 8, 9])}


In [30]:
df = pd.DataFrame(dct)
df.index = ['A', 'B', 'C', 'D']
print(df)

   aple  oranges
A     1        6
B     2        7
C     3        8
D     4        9


In [31]:
# Akses elemen data frame

# by row
print(df.loc['A'])
print(df.loc['C']['aple'])
print(df.loc['C']['oranges'])
print()

#by column
print(df['aple'])
print(df['oranges'])
print()
print(df['oranges']['A'])
print(df.oranges['A'])

aple       1
oranges    6
Name: A, dtype: int64
3
8

A    1
B    2
C    3
D    4
Name: aple, dtype: int64
A    6
B    7
C    8
D    9
Name: oranges, dtype: int64

6
6
